API_QR_GEN = 'https://passport.bilibili.com/x/passport-login/web/qrcode/generate'
API_QR_POLL = 'https://passport.bilibili.com/x/passport-login/web/qrcode/poll'
API_NAV = 'https://api.bilibili.com/x/web-interface/nav'
API_UP_VIDEO = 'https://api.bilibili.com/x/space/wbi/arc/search'
API_UP_ALBUM = 'https://api.bilibili.com/x/space/album/index'
API_UP_ALBUM_DETAIL = 'https://api.vc.bilibili.com/link_draw/v1/doc/doc_list'
API_UP_ALBUM_DETAIL = 'https://api.bilibili.com/x/dynamic/feed/draw/doc_list'
